### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by ankitchandracs** [MegEngine/YOLOX#1]
File "/content/YOLOX/tools/train.py", line 115, in <module>
    assert num_gpu <= torch.cuda.device_count()
AssertionError

**Comment by FateScript** [comment]
[code](https://github.com/MegEngine/YOLOX/blob/main/tools/train.py#L82) here is not using torch any more? What's your backend? Pytorch  or MegEngine?

**Comment by ankitchandracs** [comment]
using it on google colab

**Comment by FateScript** [comment]
Seems you are using Pytorch version code, please report your issue in another repo, Thx

**Comment by WMYYDREAM** [comment]
did you solved it?]
