### ISSUE TITLE
Shouldn't it be Xiaomi instead of "xiamo" in the Benchmark -- Testing Devices section?

### ISSUE THREAD

**Issue by Matt-Kou** [MegEngine/YOLOX#7]
Testing Devices

x86_64 -- Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
AArch64 -- xiamo phone mi9
CUDA -- 1080TI @ cuda-10.1-cudnn-v7.6.3-TensorRT-6.0.1.5.sh @ Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

Shouldn't it be Xiaomi phone mi9?

**Comment by FateScript** [comment]
PTAL @haolongzhangm  @xxr3376

**Comment by xxr3376** [comment]
That's right, it's a typo...
