### ISSUE TITLE
Something wrong in yolo_head.py

### ISSUE THREAD

**Issue by AlexZen1204** [MegEngine/YOLOX#9]
![image](https://user-images.githubusercontent.com/50004420/174278807-99a7d662-1ced-4af9-a7a0-4ba35933ad0c.png)
it should be like this ：
yv, xv = meshgrid...

**Comment by FateScript** [comment]
Could you also tell me the reason of doing this?

**Comment by AlexZen1204** [comment]
> Could you also tell me the reason of doing this?
“def get_in_boxes_info” gets x_shifts and y_shifts from “def get_output_and_grid”. If the input has the same length and width, it's ok, or it gets wrong shifts.
More, this is the “def get_output_and_grid” in yolox of torch version .
![image](https://user-images.githubusercontent.com/50004420/174564432-38cf5ae8-441d-4376-aba3-db4fb6302a65.png)
